# Generated by Django 5.0.4 on 2024-04-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modifield_date',
            new_name='modified_date',
        ),
    ]
